runtime: go121

instance_class: F1
service: daily-quote -- default

env_variables:
  DB_NAME:
  DB_USER:
  DB_PASS:
  INSTANCE_CONNECTION_NAME:
  CORS_ORIGIN: 'https://tintaindeleble.com'
  EMAIL_TEMPLATE_ID:
  MAILERSEND_API_KEY: